before_script:
  - apk update
  - apk --no-cache add py3-pip python3 curl
  - pip3 install pyyaml
  - curl -O https://raw.githubusercontent.com/FredHutch/swarm-build-helper/main/build_helper.py 
  # below is from https://stackoverflow.com/a/65810302/470769
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  - curl -LO https://releases.rancher.com/cli/v0.6.2/rancher-linux-amd64-v0.6.2.tar.gz
  - tar zxf rancher-linux-amd64-v0.6.2.tar.gz
  - set -x

stages:
  - build
  - test
  - deploy


build:
  stage: build
  script: |
    # python3 build_helper.py --n docker-compose.yml > /dev/null
    docker build -t sc-registry.fredhutch.org/covid19vaccinesimulator:test .
    docker push sc-registry.fredhutch.org/covid19vaccinesimulator:test
    sleep 5

test:
  stage: test
  services: 
    - name: sc-registry.fredhutch.org/covid19vaccinesimulator:test
      alias: covid19vaccinesimulator
  script: |
    sleep 10
    # CONTAINER_ID=$(docker ps | grep sc-registry.fredhutch.org__covid19vaccinesimulator- | cut -d' ' -f1)
    # env
    # curl -si http://covid19vaccinesimulator
    # docker logs $CONTAINER_ID
    curl -sI http://covid19vaccinesimulator | head -1 | grep -q "200 OK"
  



deploy:
  stage: deploy
  only:
    refs:
        - master
  script: |
    docker tag sc-registry.fredhutch.org/covid19vaccinesimulator:test sc-registry.fredhutch.org/covid19vaccinesimulator:latest
    docker push sc-registry.fredhutch.org/covid19vaccinesimulator:latest
    sleep 15
deploy:
  stage: deploy
  only:
    refs:
       - main
  script: |
    docker tag sc-registry.fredhutch.org/wiki:test sc-registry.fredhutch.org/wiki:latest
    docker tag sc-registry.fredhutch.org/wiki_search:test sc-registry.fredhutch.org/wiki_elasticsearch:latest
    rancher-v0.6.2/rancher --url https://ponderosa.fhcrc.org --access-key $RANCHERAPI_KEY --secret-key $RANCHERAPI_SECRET up -d --pull --force-upgrade --confirm-upgrade --stack covid19vaccinesimulator --file docker-compose.yml --rancher-file rancher-compose.yml
    # - echo $SC_SWARM_CICD_SSH_KEY | base64 -d > ./sc_swarm_cicd_ssh_key
    # - chmod 0400 ./sc_swarm_cicd_ssh_key
    # - python3 build_helper.py docker-compose.yml | ssh -i ./sc_swarm_cicd_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@sc-swarm-mgr.fhcrc.org docker stack deploy --with-registry-auth -c - covid19vaccinesimulator
